# Deploy Jenkins DevOps container locally
version: '3.2'

services:
  jenkops:
    image: phelun/jenkins_compose_image:0.2
    hostname: jenkins
    ports:
    - "80:8080/tcp"
    - "50000:50000/tcp"
    networks:
    - demo_overlay_net
    volumes:
    - ./jenkins_home:/var/jenkins_home
    - ./jenkins_backup:/tmp/backup/hudson
    - /var/run/docker.sock:/var/run/docker.sock

networks:
  demo_overlay_net:
